_wandb:
    value:
        cli_version: 0.24.0
        e:
            ozzsqnocoqjcnastq5mwn782ilzh4oyf:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "2147483648"
                args:
                    - config/basic.py
                    - --dataset=basic
                    - --device=cpu
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "259471065088"
                email: goday@dickinson.edu
                executable: /Users/youssifsalah/Desktop/CS Projects/comp research/comp560-youssif/.venv/bin/python
                git:
                    commit: bbc60792b84528ba3b1ad01ddd2d04cabe49e6a6
                    remote: https://github.com/YoussifGoda/comp560-youssif.git
                host: Youssifs-MacBook-Pro-52.local
                memory:
                    total: "8589934592"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/youssifsalah/Desktop/CS Projects/comp research/comp560-youssif/add-parenthese/../../comp560-nanoGPT/train.py
                python: CPython 3.12.2
                root: /Users/youssifsalah/Desktop/CS Projects/comp research/comp560-youssif/add-parenthese
                startedAt: "2026-01-28T16:20:36.875178Z"
                writerId: ozzsqnocoqjcnastq5mwn782ilzh4oyf
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.12.2
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
always_save_checkpoint:
    value: true
backend:
    value: nccl
batch_size:
    value: 12
beta1:
    value: 0.9
beta2:
    value: 0.99
bias:
    value: false
block_size:
    value: 64
compile:
    value: false
dataset:
    value: basic
decay_lr:
    value: true
device:
    value: cpu
dropout:
    value: 0
dtype:
    value: float16
eval_interval:
    value: 50
eval_iters:
    value: 20
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: scratch
learning_rate:
    value: 0.001
log_interval:
    value: 1
lr_decay_iters:
    value: 500
max_iters:
    value: 500
min_lr:
    value: 0.0001
n_embd:
    value: 128
n_head:
    value: 4
n_layer:
    value: 4
out_dir:
    value: out/basic
wandb_log:
    value: true
wandb_project:
    value: add-parentheses-basic
wandb_run_name:
    value: first run
warmup_iters:
    value: 0
weight_decay:
    value: 0.1
